apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: christianloewel-poi-map-app-dev
  annotations:
    argocd/app-name: christianloewel-poi-map-app-dev
    backstage.io/kubernetes-id: christianloewel-poi-map-app
    backstage.io/kubernetes-namespace: christianloewel
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh23-lab/christianloewel-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-m9x67.dusy.p1.openshiftapps.com/dev-pipelines/ns/christianloewel/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-m9x67.dusy.p1.openshiftapps.com/k8s/ns/christianloewel/deployments/christianloewel-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-m9x67.dusy.p1.openshiftapps.com/#https://github.com/rhdh23-lab/christianloewel-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://christianloewel-poi-map-app-christianloewel.apps.rosa-m9x67.dusy.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/christianloewel"
  system: workshop-system-christianloewel
  consumesApis:
    - gateway-api-christianloewel
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-christianloewel
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/christianloewel"
